apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hg154std8-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hg154std8-dotnet-basic-gitops